/*                                                                                                                                                                     
 *  startup.S
 *
 *  brif
 *      system startup
 *  
 *  (C) 2024.12.31 <hkdywg@163.com>
 *
 *  This program is free software; you can redistribute it and/r modify
 *  it under the terms of the GNU General Public License version 2 as
 *  published by the Free Software Foundation.
 * */

	.global Reset_Handler
	.section ".start", "ax"
Reset_Handler:
	nop
